/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package food_bank;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class LoginUI extends javax.swing.JFrame {

    /**
     * Creates new form LoginUI
     */
    public LoginUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CboxShowP = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        lblUname = new javax.swing.JLabel();
        btn_login = new javax.swing.JLabel();
        lblPword = new javax.swing.JLabel();
        txtPword = new javax.swing.JPasswordField();
        txtUname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("iFoodBank");
        setBackground(new java.awt.Color(47, 62, 119));
        setForeground(new java.awt.Color(47, 62, 119));
        setMinimumSize(new java.awt.Dimension(400, 500));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(47, 62, 119));
        jPanel1.setLayout(null);

        CboxShowP.setText("Show Password");
        CboxShowP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboxShowPActionPerformed(evt);
            }
        });
        jPanel1.add(CboxShowP);
        CboxShowP.setBounds(150, 340, 200, 24);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 50, 130, 140);

        lblUname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/un-img.png"))); // NOI18N
        jPanel1.add(lblUname);
        lblUname.setBounds(63, 211, 38, 38);

        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login-btn.png"))); // NOI18N
        btn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_loginMouseClicked(evt);
            }
        });
        jPanel1.add(btn_login);
        btn_login.setBounds(80, 390, 260, 50);

        lblPword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pwd-img.png"))); // NOI18N
        jPanel1.add(lblPword);
        lblPword.setBounds(63, 284, 38, 38);

        txtPword.setText("jPasswordField1");
        jPanel1.add(txtPword);
        txtPword.setBounds(149, 284, 200, 38);

        txtUname.setText("Username");
        txtUname.setFocusTraversalPolicyProvider(true);
        jPanel1.add(txtUname);
        txtUname.setBounds(149, 211, 200, 38);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg-img.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-90, 60, 770, 630);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, -10, 440, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseClicked
        // TODO add your handling code here:
        String un = txtUname.getText();
        String pw = String.valueOf(txtPword.getPassword());
        
        if (un == null){
            JOptionPane.showMessageDialog(rootPane, "Username is empty");
        }else if (pw == null){
            JOptionPane.showMessageDialog(rootPane, "Password is empty");
        }else if ("shahman".equals(un) && "admin".equals(pw)) {
            dispose();
            new MainMenuUI().setVisible(true);
        }
    }//GEN-LAST:event_btn_loginMouseClicked

    private void CboxShowPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboxShowPActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_CboxShowPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CboxShowP;
    private javax.swing.JLabel btn_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPword;
    private javax.swing.JLabel lblUname;
    private javax.swing.JPasswordField txtPword;
    private javax.swing.JTextField txtUname;
    // End of variables declaration//GEN-END:variables
}
